title: Pinetree408
author: pinetree408
email: pinetree408@gmail.com
baseurl: ""
url: "http://pinetree408.github.io/"

timezone: UTC
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "https://bit.ly/2DM2s8d"
 - name: "Contact"
   link: "contact"
